Repository Evgeniya-star-35/team-project-demo, pull requests merged in 2021-05, with the labels that each got.

#1 remove exxample pictures
  src/images/demo.jpg
Labels: help wanted

#2 add container style
  src/sass/_base.scss
Labels: question

#4 add placeholders
  src/sass/_base.scss
  src/sass/main.scss
  src/sass/utils/_placeholders.scss
Labels: check-проверь-перевір

#7 discription
  src/index.html
  src/partials/about-us.html
  src/partials/contact.html
  src/partials/footer.html
  src/partials/header.html
  src/partials/menu.html
  src/partials/program.html
  src/partials/registration.html
  src/partials/reviews.html
  src/sass/_base.scss
Labels: documentation

#17 add mark-up
  src/partials/program.html
Labels: help wanted

#14 menu.html
  js/menu.js
  src/images/logo/logo-min.png
  src/images/logo/logo@2x-min.png
  src/partials/menu.html
Labels: done

#30 add style to rogram__description div
  src/partials/program.html
  src/sass/_program.scss
  src/sass/utils/_variables.scss
Labels: help wanted

#34 add style to program__window-case div
  src/sass/_program.scss
  src/sass/utils/_variables.scss
Labels: help wanted

#38 fix-semantic-bag
  src/partials/program.html
Labels: done

#36 Lmenu
  src/index.html
  src/js/menu.js
  src/partials/menu.html
Labels: check-проверь-перевір

#41 make button openLess
  src/index.html
  src/js/moreLess.js
  src/partials/program.html
  src/sass/_program.scss
Labels: check-проверь-перевір, documentation, done

#49 look at change
  src/partials/program.html
  src/sass/_program.scss
Labels: check-проверь-перевір, help wanted

#57 add to media 768
  src/sass/_program.scss
Labels: check-проверь-перевір

#55 Слайдер
  images/reviews/elisabeth.png
  images/reviews/elisabeth110.png
  images/reviews/elisabeth110@2x.png
  images/reviews/elisabeth@2x.png
  images/reviews/john.png
  images/reviews/john110.png
  images/reviews/john110@2x.png
  images/reviews/john@2x.png
  images/reviews/mobile/behrouz1-min.png
  images/reviews/mobile/behrouz1@2x-min.png
  images/reviews/rate.svg
  images/reviews/tablet/behrouz1-min.png
  images/reviews/tablet/behrouz1@2x-min.png
  images/reviews/tablet/daniil1-min.png
  images/reviews/tablet/daniil1@2x-min.png
  images/reviews/tablet/sasani1-min.png
  images/reviews/tablet/sasani1@2x-min.png
  images/reviews/will.png
  images/reviews/will110.png
  images/reviews/will110@2x.png
  images/reviews/will@2x.png
  package-lock.json
  package.json
  src/images/reviews/elisabeth.png
  src/images/reviews/elisabeth110.png
  src/images/reviews/elisabeth110@2x.png
  src/images/reviews/elisabeth@2x.png
  src/images/reviews/john.png
  src/images/reviews/john110.png
  src/images/reviews/john110@2x.png
  src/images/reviews/john@2x.png
  src/images/reviews/mobile/behrouz1-min.png
  src/images/reviews/mobile/behrouz1@2x-min.png
  src/images/reviews/rate.svg
  src/images/reviews/tablet/behrouz1-min.png
  src/images/reviews/tablet/behrouz1@2x-min.png
  src/images/reviews/tablet/daniil1-min.png
  src/images/reviews/tablet/daniil1@2x-min.png
  src/images/reviews/tablet/sasani1-min.png
  src/images/reviews/tablet/sasani1@2x-min.png
  src/images/reviews/will.png
  src/images/reviews/will110.png
  src/images/reviews/will110@2x.png
  src/images/reviews/will@2x.png
  src/index.html
  src/js/reviews.js
  src/partials/reviews.html
  src/sass/_reviews.scss
Labels: help wanted

#63 Program8
  src/partials/program.html
  src/sass/_program.scss
Labels: check-проверь-перевір, help wanted

#67 Кнопка вверх
  src/images/sprite.svg
  src/index.html
  src/js/up-button.js
  src/sass/_up-button.scss
  src/sass/main.scss
Labels: done

#70 add changes
  src/sass/_program.scss
Labels: check-проверь-перевір

#77 bug-fix connect to js in index.html
  src/index.html
Labels: check-проверь-перевір, done

#81 add ::before, change padding to margin
  src/partials/program.html
  src/sass/_program.scss
Labels: check-проверь-перевір, done

#88 Исправил пагинацию
  src/sass/_reviews.scss
Labels: done

#96 read me button
  src/js/moreLess.js
  src/partials/program.html
  src/sass/_program.scss
  src/sass/main.css
  src/sass/main.css.map
Labels: check-проверь-перевір, done

#97 исправил проблемы секции
  src/js/id-smooth-scrolling.js
  src/js/reviews.js
  src/sass/_reviews.scss
Labels: done

#114 delete moreLess
  src/partials/program.html
Labels: check-проверь-перевір

#117 change h4 to h3
  src/partials/program.html
  src/sass/main.css
  src/sass/main.css.map
Labels: check-проверь-перевір, help wanted

#118 change mark
  src/partials/program.html
Labels: check-проверь-перевір, help wanted
